### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by toluwajosh** [YaphetS-X/CenterNet-MobileNetV3#2]
Very straightforward and simple implementation of the model. Great job.
Would you mind adding a license to the repo so as to know the permissions of using your repo.
Thanks

**Comment by YaphetS-X** [comment]
Please refer to the original License of these projects (See [CenterNet](https://github.com/xingyizhou/CenterNet) and [MobileNetV3](https://github.com/xiaolai-sqlai/mobilenetv3)).
