### ISSUE TITLE
Could you please explain what happens at this line.

### ISSUE THREAD

**Issue by toluwajosh** [YaphetS-X/CenterNet-MobileNetV3#3]
Thank you for your prompt response. Could you explain this line. I am not very familiar with the use of the `__getattr__` function.
https://github.com/YaphetS-X/CenterNet-MobileNetV3/blob/7aece407b627ee6efdb225af70b3ee644bb0dad9/lib/models/networks/mobilenet.py#L208

**Comment by YaphetS-X** [comment]
That corresponds to the `__setattr__` function.
https://github.com/YaphetS-X/CenterNet-MobileNetV3/blob/7aece407b627ee6efdb225af70b3ee644bb0dad9/lib/models/networks/mobilenet.py#L178
We use `__setattr__` function to set attributes like `self.hm` (the heatmap head) and `self.wh` (the width and height head) for the model, and in the forward process we use `__getattr__` function to get the heatmap and wh network.
