### ISSUE TITLE
大神，只需要增加mobienet.py，然后在createmodel的时候调用就行了吗？

### ISSUE THREAD

**Issue by Chris1279** [YaphetS-X/CenterNet-MobileNetV3#4]
大神，只需要增加mobienet.py，然后在createmodel的时候调用就行了吗？
还需要别的改动吗？

**Comment by YaphetS-X** [comment]
> 大神，只需要增加mobienet.py，然后在createmodel的时候调用就行了吗？
> 还需要别的改动吗？

可以直接调用，传参会有些该动，debug一下就行
